name: fsspec-reference-maker
channels:
  - conda-forge
  - default
dependencies:
  - pangeo-notebook==2021.09.30
  - pip
  - fsspec-reference-maker
  - fsspec
  - s3fs
  - h5py
  - xarray[complete]
  - metpy
  - cartopy
  - cfgrib
  - eccodes
  - numpy<=1.20.0
  - zstandard
  - hvplot
  - geoviews
  - intake
  - intake-xarray
  - datashader
  - tornado>=6.1.0
  - pip:
    - graphviz
